// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZqkwHnQJQppjLIeHwoLASccw8IGNjpQ',
    appId: '1:301075644463:web:40ab9ada0298f1751546da',
    messagingSenderId: '301075644463',
    projectId: 'backend-golang-36784',
    authDomain: 'backend-golang-36784.firebaseapp.com',
    storageBucket: 'backend-golang-36784.firebasestorage.app',
    measurementId: 'G-4GN5H6VNXF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDssx6FYZbwvsjZLMB9gEK9QPklzRot2ZI',
    appId: '1:301075644463:ios:92436331b0432de11546da',
    messagingSenderId: '301075644463',
    projectId: 'backend-golang-36784',
    storageBucket: 'backend-golang-36784.firebasestorage.app',
    iosBundleId: 'com.example.pasarMalam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDssx6FYZbwvsjZLMB9gEK9QPklzRot2ZI',
    appId: '1:301075644463:ios:92436331b0432de11546da',
    messagingSenderId: '301075644463',
    projectId: 'backend-golang-36784',
    storageBucket: 'backend-golang-36784.firebasestorage.app',
    iosBundleId: 'com.example.pasarMalam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArZqkwHnQJQppjLIeHwoLASccw8IGNjpQ',
    appId: '1:301075644463:web:364af545686b0dbf1546da',
    messagingSenderId: '301075644463',
    projectId: 'backend-golang-36784',
    authDomain: 'backend-golang-36784.firebaseapp.com',
    storageBucket: 'backend-golang-36784.firebasestorage.app',
    measurementId: 'G-7NCXLW4ML7',
  );
}
